jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Node6:
        NODE_VERSION: '6.x'
      NodeLatest:
        NODE_VERSION: '>10.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
        checkLatest: 'true'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        netstat -a
      displayName: 'netstat'         
    - script: |
        npm test
      displayName: 'npm test'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/junit.xml'
        testRunTitle: Linux $(NODE_VERSION)
      displayName: 'Publish test results'
      condition: always()

- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Node7:
        NODE_VERSION: '7.x'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: $(NODE_VERSION)
        checkLatest: 'true'
      displayName: 'Install Node.js'
    - script: |
        npm install
      displayName: 'npm install'
    - script: |
        netstat -a
      displayName: 'netstat'      
    - script: |
        npm test
      displayName: 'npm test'
    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/junit.xml'
        testRunTitle: Windows $(NODE_VERSION)
      displayName: 'Publish test results'
      condition: always()
